pipeline {
    agent none
    stages{
        stage('Set up Python') {
            agent {
                docker {
                    image 'python' 
                }
            }
            steps {
                sh '''
                    #!/bin/sh
                    cd CodingBuddy
                    virtualenv --python=python3.12 env
                    env/bin/pip install -r requirements.txt
                    python -m py_compile manage.py
                '''
            }
        }


        stage('Run Tests') {
            agent{
                docker {
                    image 'python' 
                }
            }
                steps {
                    sh '''
                        cd CodingBuddy
                        python manage.py jenkins --enable-coverage
                    '''
                }
           
        }
    }
    
    post {
        always {
            junit 'CodingBuddy/test-reports/*.xml'
        }
    }
}
