pipeline {
    agent none
    stages{
        stage('Set up Python') {
            agent {
                docker {
                    image 'python' 
                }
            }
            steps {
                sh '''
                    #!/bin/sh
                    cd CodingBuddy
                    python -m py_compile manage.py
                '''
            }
        }

        stage('Run Migrations') {
            steps {
                sh '''
                    python manage.py migrate
                '''
            }
        }

        stage('Run Tests with Coverage') {
            steps {
                sh '''
                    coverage run --source='.' manage.py test
                    coverage xml
                '''
            }
        }
    }
    post {
        always {
            junit 'CodingBuddy/reports/*.xml'
        }
    }
}
