# Generated by Django 5.0.6 on 2024-07-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeproblem',
            name='problem',
            field=models.CharField(max_length=100),
        ),
    ]
