# Generated by Django 5.0.6 on 2024-07-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBapp', '0002_alter_codeproblem_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeproblem',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
