# Generated by Django 5.0.6 on 2024-07-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBapp', '0003_codeproblem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeproblem',
            name='solution',
            field=models.CharField(default='', max_length=100),
        ),
    ]
