# Generated by Django 5.0.6 on 2024-07-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBapp', '0004_codeproblem_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeproblem',
            name='status',
            field=models.CharField(default='not accepted', max_length=20),
        ),
    ]
