# Generated by Django 5.0.6 on 2024-07-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBapp', '0005_codeproblem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeproblem',
            name='language',
            field=models.CharField(default='Python', max_length=50),
            preserve_default=False,
        ),
    ]
