# Generated by Django 5.0.7 on 2024-07-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBapp', '0006_codeproblem_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('medium_link', models.URLField(blank=True, null=True)),
                ('wikipedia_link', models.URLField(blank=True, null=True)),
                ('language', models.CharField(choices=[('c', 'C'), ('python', 'Python'), ('java', 'Java')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='solution',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
